### PR TITLE
refactored landing page and lightboxes

### PR DESCRIPTION
**Pull request by ssk13**
The banner image is temporary - just until we settle on a design

### CODE REVIEW

**Comment by hxghhhh** [comment]
@czkamin @DannyRL

**Comment by czkamin** [comment]
looks good

**Comment by DannyRL** [comment]
Looks good to me too. 

When the window is re-sized small enough, the options in the header disappear and are replaced with a menu button. But when I click on the menu button, nothing happens. Not sure if that's something to be too concerned of now, but just wanted to mention it!

**Comment by ssk13** [comment]
updated with fixed mobile navigation - thanks for pointing it out, Danny! Overwrote some materialize code

**Pull request merged**
