### PR TITLE
moved/styled sign-in lightbox and made it communicate with DB

### PR DESCRIPTION
**Pull request by ssk13**
sign in/out should work in mobile and full view - "forgot your password" doesn't work

you can test with:
username: ssk13
password: Spektor405!

[these are in the DB]

### CODE REVIEW

**Comment by hxghhhh** [comment]
@czkamin @amahfood

**Comment by amahfood** [comment]
I think it looks good. Wondering if we should make it "login" instead of "sign in" and "sign up." Maybe "Login" and "Create Account." I didn't see a way to sign out. And I think the username should be displayed somewhere on the page after logging in. Other than that, looks pretty awesome.

**Comment by ssk13** [comment]
it _should_ have your name and the option to log out if you're logged in - is this not happening for you?

**Comment by amahfood** [comment]
Nevermind! I'm still learning git! Looks all good :+1:

**Comment by czkamin** [comment]
When you resize you lose "Sarah Klein" and the log out is moved to the menu bar. I think your name should still be in the top right just to keep it uniform. All else looks awesome!

**Pull request merged**
