### PR TITLE
Log contact forms

### PR DESCRIPTION
**Pull request by DannyRL**
Contact forms can now be pushed and pulled from the DB. Admin user can access them through the website directly.

Changes/additions:
1) Lots of code to get push and pull to DB working. Still similar to Jobs and Referrals though, with a little less functionality
2) List- and view- views made that only the Admin should be able to access
3) Added link to Admin's dropdown menu so they can access the Contact views
4) Threw in a line of code that formats the date on the Careers page because Diego was trying to figure that out
5) Made the email associated with the contact form a link that should automatically open up your email client.

Known bug:
1) To mark a Contact as read or unread, I have an ng-show controlling which buttons displays on the screen. However when I press the button, the other button appears on screen for a split second while the website refreshes. It isn't a functionality bug, but it still bothers me. I'm not sure how to "slow down" the check or something to prevent this from happening

### CODE REVIEW

**Comment by hxghhhh** [comment]
@Dannyrl back merge 😛😎😇

**Comment by hxghhhh** [comment]
@DannyRL backMERGE

**Comment by hxghhhh** [comment]
@dnol777 @czkamin11

**Comment by hxghhhh** [comment]
@dnol777 @czkamin please review when you can

**Comment by czkamin** [comment]
hit forbidden page when submitted... already talked to @DannyRL

**Comment by dnol777** [comment]
:+1: Looks good to me. Already talked to Daniel about the change in the schema

**Pull request merged**
