### PR TITLE
reset state when canceling sign-in and deleted old file

### PR DESCRIPTION
**Pull request by ssk13**
Now resets state to 'home' rather than 'sign-in' when you're leaving the sign-in lightbox, which keeps it from automagically signing you in
Also, we have an old file that we're not using anymore...

### CODE REVIEW

**Comment by hxghhhh** [comment]
@DannyRL @amahfood

**Comment by DannyRL** [comment]
Not sure if necessary, but is it possible to clear the text field after pressing Cancel? Other than that, everything else is good!

**Comment by ssk13** [comment]
@DannyRL I'll look into that tomorrow

**Comment by ssk13** [comment]
updated!

**Comment by DannyRL** [comment]
Nice! Yeah, everything else looks good!

**Comment by amahfood** [comment]
Looks good to me! :+1:

**Pull request merged**
